# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('none', 'Unknonw'), ('wordpress', 'WordPress')], default='none', max_length=50, null=True)),
                ('last_crawl', models.DateTimeField(blank=True, null=True, verbose_name='Last crawl')),
            ],
        ),
    ]
