# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.CharField(choices=[('none', 'Unknown'), ('wordpress', 'WordPress')], default='none', max_length=50, null=True),
        ),
    ]
