# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('domain',), 'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AlterModelOptions(
            name='subdomain',
            options={'ordering': ('subdomain',), 'verbose_name': 'Subdomain', 'verbose_name_plural': 'Subdomains'},
        ),
        migrations.AlterModelOptions(
            name='tld',
            options={'ordering': ('tld',), 'verbose_name': 'TLD', 'verbose_name_plural': 'TLDs'},
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set([('domain', 'tld')]),
        ),
        migrations.AlterUniqueTogether(
            name='subdomain',
            unique_together=set([('subdomain', 'domain')]),
        ),
    ]
