# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0002_auto_20160910_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
