# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 11:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0003_auto_20160910_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='domain',
            name='tld',
        ),
        migrations.AlterUniqueTogether(
            name='subdomain',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='domain',
        ),
        migrations.AlterField(
            model_name='pluginresult',
            name='scan_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_result', to='domains.Domain'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='subdomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='domains.Subdomain'),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Subdomain',
        ),
        migrations.DeleteModel(
            name='TLD',
        ),
    ]
