# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0004_auto_20160528_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.CharField(choices=[(None, 'Unknown'), ('wordpress', 'WordPress')], default=None, max_length=50, null=True),
        ),
    ]
