# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0005_auto_20160911_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanerror',
            name='type',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
