# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0005_auto_20160904_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('wordpress', 'WordPress')], default=None, max_length=50, null=True),
        ),
    ]
