# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyder', '0006_scanerror_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginresult',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
