# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-15 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_subdomain_last_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='last_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
