# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_subdomain_last_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='tld',
            name='tld',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
