# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20161022_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tld',
            name='tld',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
    ]
