# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='discovered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovered', to='domains.Subdomain'),
        ),
    ]
