# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_remove_subdomain_discovered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
